### PR TITLE
updated README

### PR DESCRIPTION
**Pull request by speedtreammanga**
Added link to https://www.npmjs.com/package/filestack-js which displays all the available options.

### CODE REVIEW

**Comment by samuxyz** [comment]
@speedtreammanga Please fix the conflicts then i guess we can merge.

**Comment by timgivois** [comment]
@speedtreammanga Will you still work in this PR or may I take ownership of it?

**Comment by speedtreammanga** [comment]
you can work on it

**Comment by AndrzejSala** [comment]
It looks like changes of README.md file are on master branch already.

**Pull request closed without merging**
